In [1]:
# Imports
import numpy as np
import calc_cld
import importlib
import pingouin as pg

In [2]:
importlib.reload(calc_cld);

In [3]:
# Load some test data#
penguins = pg.read_dataset("penguins")
penguins_tk_results = penguins.pairwise_tukey(dv='body_mass_g', between='species')
penguins_tk_results

,A,B,mean(A),mean(B),diff,se,T,p-tukey,hedges
0,Adelie,Chinstrap,3700.662252,3733.088235,-32.425984,67.511684,-0.480302,0.880667,-0.073946
1,Adelie,Gentoo,3700.662252,5076.016260,-1375.354009,56.147971,-24.495169,0.000000,-2.860201
2,Chinstrap,Gentoo,3733.088235,5076.016260,-1342.928025,69.856928,-19.223978,0.000000,-2.875327

In [4]:

group_1_col, group_2_col, pvals = list(penguins_tk_results['A']), list(penguins_tk_results['B']), list(penguins_tk_results['p-tukey'])

final_letters = calc_cld.run_clc(group_1_col, group_2_col, pvals)
print(final_letters)

CLD valid: True
{'Adelie': 'a', 'Chinstrap': 'a', 'Gentoo': 'b'}

In [5]:
penguins_tk_results

,A,B,mean(A),mean(B),diff,se,T,p-tukey,hedges
0,Adelie,Chinstrap,3700.662252,3733.088235,-32.425984,67.511684,-0.480302,0.880667,-0.073946
1,Adelie,Gentoo,3700.662252,5076.016260,-1375.354009,56.147971,-24.495169,0.000000,-2.860201
2,Chinstrap,Gentoo,3733.088235,5076.016260,-1342.928025,69.856928,-19.223978,0.000000,-2.875327